### ISSUE TITLE
Require support  for generate jni library

### ISSUE THREAD

**Issue by massacreduck** [mshockwave/PdfiumAndroid#6]
I've encountered the following error when trying to build the jni library  in the jni folder

make: **\* No rule to make target `out/vivapro_evt0R_qisda/target/product/msm8974/obj/SHARED_LIBRARIES/aospPdfium_intermediates/export_includes', needed by`out/vivapro_evt0R_qisda/target/product/msm8974/obj/SHARED_LIBRARIES/jniPdfium_intermediates/import_includes'.  Stop.

In addition, I' m kind of new for shared library.
May I ask what is the file "libandroid-ndk-profiler.a" for?  
I googled it ,  Is it just for analysis ?

**Comment by weitzj** [comment]
Just so you know: This is already in maven:
http://search.maven.org/#artifactdetails%7Ccom.github.mshockwave%7Cpdfium%7C1.0.0%7Caar.asc

`compile 'com.github.mshockwave:pdfium:1.0.0@aar'`

**Comment by massacreduck** [comment]
Really really thank for your help

I wouldn't find it or finish this job on my own
even if I manually copied the files: export_includes, and libpdfium.so
I still see errors which seems to be caused by cpp reference c functions. 

/arm/arm-linux-androideabi-4.7/bin/../lib/gcc/arm-linux-androideabi/4.7/../../../../arm-linux-androideabi/bin/ld: error: cannot find -laospPdfium.so
packages/apps/oem_apps/UltraSound/pdfium/jni/./src/mainJNILib.cpp:62: error: undefined reference to 'FPDF_CloseDocument'
packages/apps/oem_apps/UltraSound/pdfium/jni/./src/mainJNILib.cpp:35: error: undefined reference to '__android_l

**Comment by weitzj** [comment]
Maybe this is interesting for you, too: https://jitpack.io
